engines:
  tslint:
    enabled: true
    config: tslint.json
    checks:
      semicolon:
        enabled: false
      whitespace:
        enabled: false
      no-unused-expression:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
    - "**.ts"
exclude_paths:
  - .circleci
  - .github
  - .vscode
  - build
  - coverage
  - node_modules
  - tests
  - component_tests
  - "**/*.js"
