swagger: "3.0"
info:
  title: Wodbook API
  version: 0.0.1
  description: >-
    ## About

    The Wodbook API is a back-end for a mobile application that helps
    you keep track of all your CrossFit related things like workouts
    and movements.
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  bearer:
    type: apiKey
    name: Authorization
    in: header
security:
  - bearer: []
paths:
