version: "2.1"

services:
  mongo:
    image: mongo:4.0
    container_name: mongo
    restart: always
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/wodbook-api --quiet | grep -q "1"
      interval: 5s
      timeout: 5s
      retries: 12
    ports:
      - "27017:27017"
    command: --smallfiles
