version: "2.1"

services:
  wodbook-api:
    image: wodbook-api:latest
    container_name: wodbook-api
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - SERVER__HOST=0.0.0.0
      - SERVER__PORT=43210
      - AUTH__SECRET=cHVibGljS2V5
      - MONGO__URI=mongodb://mongo:27017
      - MONGO__DB_NAME=wodbook-test
      - RUST_LOG=info,actix_web=debug
    ports:
      - "43210:43210"
    cpu_shares: 100
    mem_limit: 512M

  mongo:
    image: mongo:4.0
    container_name: mongo
    restart: always
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/wodbook-api --quiet | grep -q "1"
      interval: 5s
      timeout: 5s
      retries: 12
    ports:
      - "27017:27017"
    command: --smallfiles

  wait-dependencies:
    image: willwill/wait-for-it:latest
    depends_on:
      wodbook-api:
        condition: service_healthy
    entrypoint: /bin/sh
    command: >
      -c "./wait-for-it.sh wodbook-api:43210 --strict --timeout=60"
