version: '2'

services:
  wodbook-api:
    image: wodbook-api:latest
    container_name: wodbook-api
    depends_on:
      mongo:
        condition: service_started
    environment:
      - ACCOUNT=dev
      - MONGO_URI=mongodb://mongo:27017/wodbook
      - MONGO_MAX_POOL_SIZE=10
    ports:
      - "43210:43210"
    cpu_shares: 100
    mem_limit: 512M
    networks:
      - wodbook_network
