version: "2.1"

services:
  wodbook-api:
    image: wodbook-api:latest
    container_name: wodbook-api
    depends_on:
      mongo:
        condition: service_started
    environment:
      - HOST=0.0.0.0
      - PORT=43210
      - AUTH__SECRET=cHVibGljS2V5
      - MONGO__URI=mongodb://mongo:27017
      - MONGO__DB_NAME=wodbook-test
      - RUST_LOG=info,actix_web=debug
    ports:
      - "43210:43210"
    cpu_shares: 100
    mem_limit: 512M
    networks:
      - wodbook_network
