version: '2.1'

networks:
  wodbook_network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.30.0.0/24
        gateway: 172.30.0.1

services:
  mongo:
    image: mongo:3.6
    container_name: mongo
    restart: always
    ports:
     - "27017:27017"
    networks:
      - wodbook_network
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
