name: audit

on:
  push:
    paths:
      - "Cargo.toml"
      - "Cargo.lock"
    schedule:
      - cron: "0 4 * * *" # “At 04:00.” (https://crontab.guru/#0_4_*_*_*)

jobs:
  security-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cache cargo bin
        uses: actions/cache@v1
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-audit
      - name: Run audit check
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
